### ISSUE TITLE
Adding voice control

### ISSUE THREAD

**Issue by evancohen** [philipptrenz/photo-booth#1]
Hey Philipp, just gauging some interest here: would you be interested in merging a PR to add voice control for the photo booth? I'm thinking instead of tapping a screen you say "cheese" and then the countdown starts.

**Comment by philipptrenz** [comment]
Hey Evan, many thanks for your support! 
This sounds great, I'm very open minded to add new features! Have you already implemented something?

**Comment by evancohen** [comment]
I haven't actually written the code for this yet, but I wrote a node module for an offline keyword spotter that I use in my smart mirror - would be easy to implement something pretty quickly :)

I'll take a stab this weekend.

**Comment by philipptrenz** [comment]
Working offline is quite important, I'm looking forward to hear from you ;)

**Comment by philipptrenz** [comment]
Hi @evancohen any progress?

**Comment by evancohen** [comment]
This totally slipped off my radar! I've got some time tonight and I'll take a stab.

**Comment by wikijm** [comment]
@evancohen Any news about this?

**Comment by evancohen** [comment]
@wikijm I got a prototype working, but I'm traveling for the next few months without access to my dev box.

**Comment by wikijm** [comment]
@evancohen 
OK, thanks for your feedback.

Enjoy your trip 😃
