### ISSUE TITLE
installing electron-rebuild returns with: command not found

### ISSUE THREAD

**Issue by pearson222** [philipptrenz/photo-booth#10]
Hi there!

Many thanks for putting this together!  

I am running into an issue when trying to execute the "npm install && ./node_modules/.bin/electron-rebuild" command.  I keep getting the response- bash: npm: command not found.  Everything else has install without any issues.  Internet connection is solid.  Any help would be much appreciated!

Thank you,
Matt

**Comment by danikuci1** [comment]
Can you run `sudo node -v` and `sudo npm -v` and share what versions are on your system? I'm guessing maybe npm isn't installed on your system?
