### ISSUE TITLE
Images are displayed in Black & White

### ISSUE THREAD

**Issue by the5issilent** [philipptrenz/photo-booth#11]
Got the app working on both Raspberry Pi 3 and macOS Sierra.

Images displayed on screen appear in black and white but are stored in full color.  Any idea what might be going on?  Duplicated on both platforms.

Thanks

**Comment by the5issilent** [comment]
Ahhh.  Figured it out 10 minutes after posting.  Modified the main.css and I'm all good now.

**Comment by philipptrenz** [comment]
Hi @the5issilent , glad you got it.
