### ISSUE TITLE
Adding RGB LED Control on photos

### ISSUE THREAD

**Issue by themaluxis** [philipptrenz/photo-booth#113]
Hey dude, thanks for your work, this project looks awesome !!

I would like to know if it could be possible to use something like ws2812b led strip as flash, connected on RPi GPIO
Is it possible to do this with your script ?

**Comment by BeneMe** [comment]
Hi themaluxi,
it can be added quite easily with the 'rpi-ws281x-native' npm module.
I'm currently working on something similar. I don't want to use the led strip as flash, at least not primarily. 
The problem i want to solve is, people tend to look at the countdown on screen and not into the camera lens. So I want to have a Led ring around the lens to display the countdown and spinner.
My ws2812 code is still work in progress: https://github.com/BeneMe/photo-booth/tree/feature/neopixel
It is a draft and there is still some work to do, I will have to change the structure a bit to add it into the app's states and make it an optional feature.
Feel free to give feedback or code improvements
