### ISSUE TITLE
no GIF symbol in the webapp

### ISSUE THREAD

**Issue by maximilianfriedrich** [philipptrenz/photo-booth#116]
Hi,

I use the default config and there is no button for GIF genereation showing up. 

@marcel-hofer Do I need to configure something more than `"gifDelay": 1000,` in the config.json?

This is what shows up currently:
![image](https://user-images.githubusercontent.com/42889526/74590217-ca2d0880-500c-11ea-99c8-7e1c7f5aa51e.png)

Thanks ahead.

**Comment by DickesHortKind** [comment]
Hi maximilianfriedrich

no, thats right. If you select more than one picture and you press the 'save' Button, the Software creates a GIF.

BR
