### ISSUE TITLE
Unable to select capture target 0

### ISSUE THREAD

**Issue by gavinvaz** [philipptrenz/photo-booth#119]
Hi,

The Nikon D90 supports the following capture targets (via `gphoto2 --get-config capturetarget`):

Choice: 0 Internal RAM
Choice: 1 Memory card

However, once you select _choice 1_ (via the config file), it is not possible to select _choice 0_ again.
Looks like the cause is the following **if statement** in the /app/camera.js file
`if (utils.getConfig().gphoto2.capturetarget) {
....
}`

Cheers,
Gavin

**Comment by mlubik** [comment]
Hello,

I nearly installed photobooth app and I have same problem. I use CanonEos250d. I was trying to switch 0 to 1 and 1 to 0 and nothing. Terminal shows always same parameters. 

@philipptrenz , we will be thankfull if you could help us with this problem.

My screen of app is black and shows nothing after take a photo.

Thanks!
Maciej
