### ISSUE TITLE
photo-booth on raspberry pi 4 4gb

### ISSUE THREAD

**Issue by SteffenLammers** [philipptrenz/photo-booth#127]
Hey guys,

I wanted to use this nice project on a new raspberry pi 4(4gb model). But when im trying to run the application with 'npm start' i get the following error with the used sharp library.

'Uncaught Error: 'linux-armv7'
binaries cannot be used on the 'linux-armv6' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-armv6' platform.'

But my raspberry pi got the armv7 architecture. Can someone help me to solve the problem?

Nice greetings

**Comment by stanglt** [comment]
Did you try a `npm rebuild sharp`?
