### ISSUE TITLE
Files Not Found

### ISSUE THREAD

**Issue by ttsepi** [philipptrenz/photo-booth#14]
Hi Philipp,

Thank you for creating this photo-booth project.

I ran the following command "sudo apt-get install git npm gphoto2 libxss-dev libgconf-2-4 libnss3" and received the following error messages:

Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libssl-dev armhf 1.0.1t-1+deb8u6
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libssl-doc all 1.0.1t-1+deb8u6
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libx11-dev armhf 2:1.6.2-3
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libx11-doc all 2:1.6.2-3
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libc-ares-dev armhf 1.10.0-2+deb8u1
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]

I am running Raspbian Jessie and do not know what to do next.  Any suggestions would be greatly appreciated.
Thanks,

Tom

**Comment by philipptrenz** [comment]
Hey @ttsepi

please check your network connection. It seems like you have no connection to the internet, it's no photo-booth related issue.

Cheers
