### ISSUE TITLE
Raspberry does not start anymore

### ISSUE THREAD

**Issue by hendrikOtto** [philipptrenz/photo-booth#17]
Hi!

I downloaded and installed everything as explained. I'm using the newest version of raspberrian. I made update and upgrade. The first start worked great as I typed ./start.sh. After reboot of the raspberry I got stuck on a login screen. While booting the raspberry shows a "Welcome to Raspberry PI Desktop" sign which is new to me. Then I get an GUI interface to login. The raspberry seems to accept the password "raspberry" but instead of login in it seems that the routine is broken and the GUI get back to the login screen. 

If I type a wrong password the raspberry shows me that the password is not valid. If I get to Crlt+Alt+F1 I'm already logged in but I cannot start a gui with startx

I am a bit confused what I should do because there is no error massage or similar. 

startx gives the error massage: "timeout in locking authority file /home/pi/.Xautority"

Greetings 
Hendrik

**Comment by hendrikOtto** [comment]
I could solve the problem temporarily with 

`cd /home/machine
mv .Xauthority .Xauthority.old
touch .Xauthority
chown raspberry .Xauthority

 cd /home/user
 ls -a -lh
 chown pi .Xauthority
 ls -a -lh`

it last exactly until I started the ./start.sh again. The same error is occurring. 
Funny fact: When I'm in console modus I cannot start the gui with startx but if I press "ctrl +c" while the raspberry tries to start, it will load the normal desktop gui.

now I also get the "timeout in locking authority file /home/pi/.Xautority" when I try to start the photobooth with ./start.sh

**Comment by philipptrenz** [comment]
Hi @hendrikOtto seems like starting the xserver directly collides with the already on xserver running Desktop with its login procedure.

Anyway, it is not recommended to start photo-booth via the `start.sh` script when using a desktop environment. I use the Raspbian Lite version without a desktop, so I have to start a xserver on my own to get windows displayed. That's the only reason for the script.

The recommended way to start photo-booth on Desktop systems is `sudo npm start` from the project directory. Maybe I should point that out better ;)
