### ISSUE TITLE
Photo booth won't take pictures after the first shot, and other odd behavior

### ISSUE THREAD

**Issue by landaunp** [philipptrenz/photo-booth#19]
Hi Philip. First off, thank you for creating this project. It is exactly what I was looking for! 

I am running this on a Raspberry Pi 3, following @JddAndrewLauren instructions. I am using a Nikon D40 with Nikon DX 18-55mm lens. 

When I run the software, turn on the camera, and click, it will take 1 pictures ONLY if the lens autofocus is set to manual. Otherwise it errors out ("Oh shit...")

If I try to take a second picture it errors out. If I turn the camera off and on again, and click, then it will take one picture. Strangely, after the count down, the camera will snap a photo, and the program it will briefly display "Oh shit..." before showing the photo. 

Additionally, I tried removing the SD card I had in the camera, and it stopped taking pictures all together regardless of rebooting, or power cycling the camera. 

Finally, I was able to get the collage in color, but I cannot get the full screen photo preview in color. Only, black and white. Where is the setting to modify that preview? 

Thank you!

**Comment by philipptrenz** [comment]
Hey @landaunp,

thanks!

## Issue 1

I also had some issues with autofocus, I think gphoto2 runs into a timeout when the camera takes too long. Take a look at the [gphoto2 documentation](http://www.gphoto.org/doc/remote/).

## Issue 2

That the images don't show up may be related to the wrong capture target settings. Run `gphoto2 --get-config capturetarget` from the console, the output looks something like this:

```
Label: Capture Target
Type: RADIO
Current: Internal RAM
Choice: 0 Internal RAM
Choice: 1 Memory card
```
Identify the number of the memory card and change the `captureTarget`property in `config.json`. You may also take a look at #4.

If this does not fix your issue please feel free to come back to me.

## Issue 3

I finally made the image styles configurable, run `git pull` from your console. Then go to `config.json` and change `grayscaleMode` to `false`.

**Comment by landaunp** [comment]
Issue 1 resolved itself some how. I'm not quite sure what did it. 

Issue 2 is resolved as well, and I apologize for not completely RTFM.

Issue 3 is also resolved thanks to your update. I got everything working so THANK YOU!

**Comment by philipptrenz** [comment]
😊👍🏼

**Comment by Charlielannie** [comment]
We have the same problem( Issue 1). Can you help us solve it?

**Comment by philipptrenz** [comment]
@Charlielannie I answered you @  #34
