### ISSUE TITLE
Android chrome can't connect to built in web-page

### ISSUE THREAD

**Issue by landaunp** [philipptrenz/photo-booth#20]
Hello again. I've got the photo booth software working on my Raspberry Pi 3. I have configured to use it as a wifi access point per the suggested official method listed here: https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md
I do not have it connected to internet via the ethernet point, and I have not set up bridging.

I can connect to it from multiple devices, and I can go to the device's IP address and see the web page from an iPhone and my PC, but when I try to access it from my Pixel2 via Chrome, I get a "connection timed out" error. 

Have you seen this before? I don't understand why it's not working only on my android. 
Thanks, as always, for providing this software and your time! I've had fun setting this all up and seeing the resulting photos.

**Comment by landaunp** [comment]
I don't know if I fixed it but I think I figured out part of the problem. Entering "192.168.4.1" into Chromes search bar tries to search google for it the address. You have to type "http://192.168.4.1". 

Additionally, I set up DNS forwarding to "photo.booth" and on all devices (PC, iPhone, Android) I had to go to "http://photo.booth", as just entering "photo.booth" would try to do a google search.  I'm not aware of any Raspberry Pi-side solutions to this. But I think this work around makes this problem more or less solved.

**Comment by philipptrenz** [comment]
Hey @landaunp,

you just have to run photo booth with root privileges. 

Please check the output of the Developer Console and post it here.

**Comment by philipptrenz** [comment]
Ah, I just saw your second comment. I know this problems, but there’s nothing we can do because every browser has its own peculiarities ...

**Comment by landaunp** [comment]
That's kinda what I figured. Thank you for weighing in.
