### ISSUE TITLE
Attempting on Pi Zero W, won't start

### ISSUE THREAD

**Issue by caraar12345** [philipptrenz/photo-booth#28]
```
> @philipptrenz/photo-booth@1.4.4 start /home/pi/photo-booth
> electron .
```

Hi,
I tried the photo booth on a Pi Zero W with no success. When I type ``sudo npm start`` or simply ``npm start``, the CPU usage jumps to 100% for a sec before the two above lines are outputted and the program quits. Same happens when started from GUI terminal as in SSH terminal.

thanks so much!

**Comment by caraar12345** [comment]
update: turns out electron and the pi zero aren't compatible

i wish I'd bothered to look this up before spending 2 hours compiling

**Comment by philipptrenz** [comment]
Hi @caraar12345,
oh okay, I didn't know that either. I will update the README so that at least others can benefit from your suffering 😉 Thanks for your report!
