### ISSUE TITLE
main photo too big

### ISSUE THREAD

**Issue by barrettl88** [philipptrenz/photo-booth#3]
Hello @philipptrenz sorry I've had to create an issue to contact you.

When I take a photo with out the console, the main image is cropped down at the bottom as if the image is too wide for the screen.

Is there any part of the code that will resize the main image so it will fit? Even if I add a margin.

Thanks in advance

**Comment by philipptrenz** [comment]
Hey,

it's all right. If I get you right you talk about the meant-to-be fullscreen image.
The preview image wrapper is defined in line 125 in css/main.css and get's loaded as background image of the div with id `#preview`. So just change the values of this div.

Did this happen at your default installation or have you tried to customize it?

**Comment by barrettl88** [comment]
Thanks for getting back to me, I changed the resolution on my pi which has helped a bit, I hadn't changed anything on it this is the code:

position: fixed;
    padding:0;
    margin:0;

    top:0;
    left:0;

    width: 100%;
    height: 100%;

    z-index: 10000;
    background-size: cover;
    background-repeat: no-repeat;

	animation: fadein 0.5s;
	animation-timing-function: ease-in;
}

**Comment by philipptrenz** [comment]
Okay, maybe it's just a pixel error. You can try to set width and height to 99.9%. If this does not help try the same on `#countdown` at line 104 and 105. If both will not fix the issue, maybe a screenshot would help me to understand the problem a bit clearer.

**Comment by philipptrenz** [comment]
Hey @barrettl88 could you solve it?

**Comment by barrettl88** [comment]
Hello Phillip, I don't think I did, I think I changed the resolution in the end.

**Comment by philipptrenz** [comment]
Okay, but you found a workaround for your case, right?
