### ISSUE TITLE
Problem with the focus

### ISSUE THREAD

**Issue by Charlielannie** [philipptrenz/photo-booth#34]
When using photo-booth, when we want to take a picture sometimes the camera can't find it's focus immediately and gphoto2 gives an error causing the programme to crash.

**Comment by philipptrenz** [comment]
Unfortunately, that's not what I can change, sorry! Most likely it's an issue of your camera or between your camera and gphoto2. You can check the gphoto2 documentation and open an issue at https://github.com/gphoto/libgphoto2
