### ISSUE TITLE
Black screen after pushing the button

### ISSUE THREAD

**Issue by m18grunling** [philipptrenz/photo-booth#36]
...webservice down and photo booth not working :-(

![20180630_035748](https://user-images.githubusercontent.com/40590441/42120403-c2a88e8a-7c1a-11e8-8a58-64ea40547a87.jpg)

**Comment by philipptrenz** [comment]
Most likely you are running a photo-booth or gphoto2 session anywhere in the background. Do a reboot and make sure you don’t have another instance running.

**Comment by m18grunling** [comment]
Hmm.. no.. when i close the application with ALT + F4 and restart.. maybe it is working.

F.e.... i make 5 photos, make a break for 4 minutes and take another photo, then it stop working :-(

**Comment by ehNorm** [comment]
I have the same problem with the blank screen, but I do not have this error. Everything seems to be fine and then it suddenly crashes after a while. I guess the app breaks down? Because everything else works fine. Is there any crash log?
CPU or GPU overload?

**Comment by philipptrenz** [comment]
@m18grunling The iussue is definitely related to gphoto2, maybe it's a bug related to your camera. Please check (forums etc) if there are known issues with gphoto2 / libgphoto2 and your camera model.

@ehNorm Please open a new issue if it is not directly related to this.
