### ISSUE TITLE
Error code: Whoops... Something went wrong when saving the photo, please try again

### ISSUE THREAD

**Issue by Berni1964** [philipptrenz/photo-booth#38]
After triggering the camera, the error code "Whoops ... Something went wrong when saving the photo, please try again" appears.

What am I doing wrong?
![img_7243](https://user-images.githubusercontent.com/40838383/42291539-9ac92b58-7fcc-11e8-874f-5229b0e63f8c.JPG)

**Comment by philipptrenz** [comment]
Please check #25

**Comment by Berni1964** [comment]
Thanks for the answer. A file will be created. But the message appears: Image file contains no data.

**Comment by Berni1964** [comment]
It works. It was due to the settings on the camera.
