### ISSUE TITLE
"sudo npm start" fails

### ISSUE THREAD

**Issue by velasco** [philipptrenz/photo-booth#40]
Hi Philipp,

with the newest Pi Stretch and your manual I'm not able to get the app started. It says:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @philipptrenz/photo-booth@1.4.4 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @philipptrenz/photo-booth@1.4.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-07-09T21_27_48_695Z-debug.log

Can you help?

**Comment by FizzyMUC** [comment]
How did you fix it?
