### ISSUE TITLE
Feature request- liveview of the camera

### ISSUE THREAD

**Issue by Tannerj5** [philipptrenz/photo-booth#41]
Not sure if I missed it in the Config files- but it would be awesome to have the background of the app be a live view from the camera. Anyone have an elegant way to have that happen?- Just realized this is a duplicate.

**Comment by Tenebrae00** [comment]
@Tannerj5 i would like to ask how this feature request ended? is there any way to start live preview or its feature that is missing in this project?

**Comment by philipptrenz** [comment]
Duplicate to #26
