### ISSUE TITLE
Push button (GPIO) does not work

### ISSUE THREAD

**Issue by c1n4pl3nr3k** [philipptrenz/photo-booth#43]
Hey there, I have connected a push button (using a 47k resistor) as mentioned in the repository. Also i started NPM with root privileges and turned on the gpio option in my.config.json. Are there any suggestions to fix that?

Kind regards
H
![screenshot](https://user-images.githubusercontent.com/43728980/46261191-45614d80-c4f0-11e8-998c-87d061144144.png)

**Comment by ghost** [comment]
Also having this issue.

**Comment by c1n4pl3nr3k** [comment]
@philipptrenz do you have any suggestion to fix the problem?

Kind regards
H

**Comment by philipptrenz** [comment]
Please enable `init.showDevTools` inside the `config.json` and report the output of the javascript console.

**Comment by c1n4pl3nr3k** [comment]
**@philipptrenz here you find my console.log:**

utils.js? [sm]:235 utils: interface wlan0 192.168.153.148
slideshow.js? [sm]:40 slideshow: enabled
booth.js? [sm]:65 GPIO usage activated
webapp_server.js? [sm]:53 webapp: listening at port 80
camera.js? [sm]:48 gphoto2: Found Canon EOS 400D (PTP mode)

**Comment by c1n4pl3nr3k** [comment]
?

**Comment by philipptrenz** [comment]
Forgot to hit "comment", sorry!

This seems perfectly fine. Make sure you're using GPIO 3 / PIN 5, I can not give any other advice. I've tested on Raspberry Pi 2 and 3 so it should not be any software related issue.

**Comment by serpentes80** [comment]
switched mine a few days ago from Touchscreen to Pushbutton following the guide.
I used a 51kOhm resistor and it works like a charm.
I would check the wiring.

**Comment by philipptrenz** [comment]
Thanks @serpentes80! So I‘ll close the issue.
