### ISSUE TITLE
Warning at installation

### ISSUE THREAD

**Issue by benoitb21** [philipptrenz/photo-booth#5]
Hello I try to install this in my raspberry pi 3,
I retried many times to understand that I must before do:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

but I have many WARN errors:

> npm WARN deprecated babel-preset-es2015@6.3.13: Thanks for using Babel: we recomment using babel-present-env now: please read babeljs.io/env to update!
> npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the lastest version of pug instead of jade
> npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
> npm WARN prefer global npm@3.10.10 should be install with -g

It's normal?

Thanks

**Comment by philipptrenz** [comment]
Hey @benoitb21 ,

sorry, that it took a while to answer your issue. Yeah, that's normal. 
The thing is the base framework electron as well as photo-booth itself uses several packages collected via the npm package manager. This packages again are using packages and so on. This results within an quite complex dependency tree and updating dependencies is quite difficult. So dependencies get freezed by defining a certain version number of the package to stay compatible. So it's quite normal to have a large number of warnings and nothing to worry about.

Philipp
