### ISSUE TITLE
No support for webcams

### ISSUE THREAD

**Issue by blak3r** [philipptrenz/photo-booth#51]
I'd suggest making the README.md more explicit that photo-booth does not currently support web cams / Make a feature request to add web-cam support.

As an optimistic user, when i read things like `Simply connect your camera via USB or even via wifi to the computer running this application,` and `Because of the use of gphoto2 it works with nearly any camera like plug and play. A list of supported devices can be found here.` I **incorrectly** assumed this included usb webcam's.  I believe the user here: #31 also made a similar mistake.

BTW - Great Project... In no way is this intended to be "snarky", "condescending" or "negative".  

### Details

Photo-Booth depends on gphoto2 for camera connection.
gphoto2 states:
```
3.1.2. | Is my webcam supported by libgphoto2 ? How can I use it ?

libgphoto2 is not meant in any way to use webcams. It only works with still image cameras, and is designed to fetch images out of the internal storage of these cameras. It also eventually can be used to remote control the camera to take pictures, it the camera has support for it and if the driver can do it. But not at all libgphoto2 has been designed to be tool to operate webcams nor do we support these devices. There are other solutions for that. Try searching Google.
```
_Source: <http://www.gphoto.org/doc/manual/FAQ.html#FAQ-webcam>_

**Comment by philipptrenz** [comment]
Hi @blak3r, thanks for your advice, constructive criticism is always welcome! And you're very right, the README.md is a bit unclear in that point.
If you want you can create a pull request, I'll also list you as the first contributor 😉
