### ISSUE TITLE
Update not supported raspi devices

### ISSUE THREAD

**Issue by Danny4927** [philipptrenz/photo-booth#54]
Not supported: Raspi Zero | Zero W / WH | 1 Mod. A | 1 Mod. A+ | 1 Mod. B | 1 Mod. B+, because of the ARMv6 architecture [see](https://de.wikipedia.org/wiki/Raspberry_Pi#Hardware), which is not supported by electron: [link](https://electronjs.org/docs/tutorial/support#linux).
Electron supports only ARM v7. (ARMv8 is backwards compatible and also works)
ARM v7: Raspi 2 Mod. B 
ARM v8: Raspi 2 Mod. B v1.2 | 3 Mod. A+ | 3 Mod. B | 3 Mod. B+

Please add this to the read me to save some people time :)
Nice project btw ;)

**Comment by philipptrenz** [comment]
Hey @Danny4927 thanks for your research, I wasn't aware of that fact!
