### ISSUE TITLE
How to quit when in full screen mode?

### ISSUE THREAD

**Issue by AdySan** [philipptrenz/photo-booth#55]
I see that the only way to quit the app is by closing the window but that becomes impossible when you're in full screen mode. Is there a way to add a hot key as mentioned in the link below?

https://stackoverflow.com/questions/37967513/exit-full-screen-when-esc-is-pressed-using-javascript-with-electron

```node
    const remote = require("electron").remote;

    document.addEventListener("keydown", event => {

        switch (event.key) {
            case "Escape":
                if (remote.getCurrentWindow().isFullScreen()) {
                    remote.getCurrentWindow().setFullScreen(false);
                }
                break;
             }
    });
```

(my node skills are very noob level, so i wasn't sure where exactly to insert this snippet)

**Comment by philipptrenz** [comment]
Hi @AdySan,

you're right, there was no way to quit the app in fullscreen. I just pushed a solution based on your "ESC key" suggestion. Thanks for the hint!
