### ISSUE TITLE
Webapp - Saving email address

### ISSUE THREAD

**Issue by hotdogreen** [philipptrenz/photo-booth#56]
Hi there, 
I’m currently playing around with your photo box software. Working great so far. 
But there’s one question left:
If I log in to the webapp it offers me the chance to enter a email. 
If I submit nothing seems to happen. Any idea how to edit the file that it saves the emails to a txt or something like that?

**Comment by philipptrenz** [comment]
Hi @hotdogreen,
the mail addresses get stored inside the `content/email-addresses.txt` while the path to the folder `content` is defined inside the `config.json`

**Comment by hotdogreen** [comment]
Thanks
