### ISSUE TITLE
App is broken after Out-of-focus exception of gphoto2

### ISSUE THREAD

**Issue by philipptrenz** [philipptrenz/photo-booth#58]
**Description:**  
Everything is working, until some stays to close to the camera and gphoto2 throws an Out-of-focus exception, then your error message appears (Whoops ….), but if you then try to make another photo by clicking left click, the app is broken (dark screen and no reaction). 
On all devices and OS versions i can crash the photo-booth app, if the camera can not do an autofocus.

From the logs:
„An error occurred in the io-library ('Could not claim the USB device'): Could not claim interface 0 (Device or resource busy). Make sure no other program (gvfs-gphoto2-volume-monitor) or kernel module (such as sdc2xx, stv680, spca50x) is using the device and you have read/write access to the device."

No automount is activated. If gphoto2 capture image command gets run via terminal,  „Out-of-Focus“ errors can be produced without crashing gphoto2.

**Test setup:** 
* Hardware: raspberry pi 3 b+ and tinker board s
* OS: raspbian, armbian stretch, armbian bionic, tinkeros
* Cameras: nikon d3200, d5300

**Comment by probststefan** [comment]
I fixed that with `getCurrentWindow().reload();` after the error is thrown.

**Comment by m18grunling** [comment]
@probststefan  Where is it necessary to add the line `getCurrentWindow().reload();`

THX!

**Comment by probststefan** [comment]
@m18grunling https://github.com/philipptrenz/photo-booth/pull/68
