### ISSUE TITLE
Error Code - "takePhoto" is not defined

### ISSUE THREAD

**Issue by DolanRN** [philipptrenz/photo-booth#6]
Hey I am just getting this error thrown whenever I try to take a photo. Any advise?

**Comment by philipptrenz** [comment]
Hey @DolanRN,

hm, this is strange. Does the photo show up or do you get just that error message?

**Comment by DolanRN** [comment]
So this error would prevent the program from even starting so no photo or
anything. I was trying this on the Raspbian OS and then I put Ubuntu on my
pi and it worked flawlessly.

**Comment by philipptrenz** [comment]
Did you use the the current Raspbian Stretch image? There have been several problems reported with Stretch. If you want to use Raspbian, take a look at the previous Raspbian Jessie.
