### ISSUE TITLE
Add emailing/sending to social media from web interface

### ISSUE THREAD

**Issue by unmanagedtn** [philipptrenz/photo-booth#65]
If you could add emailing or sending to twitter or facebook from the web interface that would kick it up... and be less clutter on the photo screen.

**Comment by philipptrenz** [comment]
Hey, do you use the photo-booth in a internet connected way? In my experience bringing my box to different events there is very rarely a wifi to connect to. But maybe you have a different experience?

**Comment by philipptrenz** [comment]
Or do you mean a feature to push the pictures from the web app to social media? This is possible (but inconvenient) by downloading a picture and then using the "Share" feature of the device
