### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by ThomasVandenabeele** [philipptrenz/photo-booth#7]
I installed nodejs on my raspberry pi 3 (nodejs version 8.9.1).
When I start the program I only see a black booth.html window.
In the developer console I see an SyntaxError: Unexpected token import at line 18 of booth.html.

I assume this has something to do with a package version mismatch? Do you know what I did wrong?

**Comment by philipptrenz** [comment]
Hi @ThomasVandenabeele which version of Raspbian do you use? There were several problems with Raspbian Stretch (with the new Pixel desktop) reported. The older Raspbian Jessie as well as the Ubuntu seem to run fine.

**Comment by philipptrenz** [comment]
I just updated the README for Raspbian Stretch support. I did not test it myself but I was told that it works that way. If it fixes your problem please let me know.

**Comment by mkomarsr** [comment]
I'm getting the same thing under Jessie.

# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
# nodejs -v
v5.12.0
# npm -v
3.8.6

**Comment by mkomarsr** [comment]
Rebuilding electron seems to have resolved it for me. Strong work!

**Comment by philipptrenz** [comment]
Thanks for the feedback @mkomarsr!
