### ISSUE TITLE
Slideshow does not always work

### ISSUE THREAD

**Issue by bionic17** [philipptrenz/photo-booth#73]
First thank you for this great project

I have the following problem:
After the first photo, the slideshow works perfectly. After more photos, the slideshow sometimes works and sometimes not -> unfortunately no pattern behind it.

I have tested the following:
- With push button
- without push button (GPIO false)
- Your default settings
- preventScreensaver (true and false)
- with boot start and manual start
 
  ...always with the same problem as described above.

**Comment by philipptrenz** [comment]
Hey @bionic17,

hm, that sounds strange. I'll take a look at it.
