### ISSUE TITLE
Error Code - An error occurred in the io-library

### ISSUE THREAD

**Issue by Hockner** [philipptrenz/photo-booth#74]
Hi guys,

after new installing photo-booth the app doesn't start any more. The error code is "An error occurred in the io-library" like at the picture attached. 

Could anybody help? Camera is Nikon D3300 or Canon 1300D. Same issue on both cameras.

Thanks!
![IMG_8555](https://user-images.githubusercontent.com/50007324/56784433-b6e84c80-67f0-11e9-9615-980599bf22e8.jpg)

**Comment by lal12** [comment]
Well, something is blocking the USB Device (as does the "Das Gerät oder die Ressource ist belegt" say). I had the same problem besides killing the mentioned "gvfs-gphoto2" processes, I tried just to look for other processes which could access my usb device.

**Comment by philipptrenz** [comment]
Hey, is the problem gone?

**Comment by andi34** [comment]
https://github.com/andi34/photo-booth/commit/81aae0418068463e7c4d1daef9a761f72781b281
