### ISSUE TITLE
Liveview

### ISSUE THREAD

**Issue by RichyJ999** [philipptrenz/photo-booth#79]
I see that liveview has now been added to the readme, but isn't working for me on my Canon EOS 1100D. gPhoto says that Liveview is supported on this camera, is there something that I need to enable?

Thanks in advance for any help!

Rich

**Comment by webworkerJoshua** [comment]
As said in the Readme file, you have to set this setting
`"live": {
		"framerate": 10
	},`
in your my.config.json or config.json. Of course you can set the framerate to a number you prefer

**Comment by RichyJ999** [comment]
The "live" option wasn't in the stock config.json and I hadn't noticed it in the readme - thank you for pointing it out!

However with the "live" option now added, I'm still not getting a preview. :( My file now reads:

```json
{
	"init": {
		"fullscreen": true,
		"width": 1440,
		"height": 900,
		"showDevTools": false,
		"useGPIO": false,
		"grayscaleMode": false,
		"preventScreensaver": true
	},
	"maxImageSize": "1500",
	"firstPhotoCountdownLength": "5",
	"followingPhotosCountdownLength": "4",
	"photoPreviewDuration": "2",
	"photoSeriesLength": "4",
	"slideshow": {
		"enabled": false,
		"activatesAfterSeconds": "30",
		"secondsPerPhoto": "8"
	},
	"gphoto2": {
		"capturetarget": 0,
		"keep": true
	},
	"triggers": {
		"onClick": true,
		"customKeys": ["PageUp","PageDown","b"]
	},
	"content_dir": "../PhotoBooth Photos",
	"webapp": {
		"password": "test",
		"maxDownloadImageSize": 800,
		"enableRemoteRelease": true
	},
	"live": {
		"framerate": 100
	},
	"branding": {
		"type": "text",
		"content": "<div style='font-size: 1.2em; padding-left: 25px;'><i class='fa fa-wifi' aria-hidden='true' style='font-size: 2.5em;'></i> <b style='font-size: 2em; padding-left: 15px;'>photo-booth</b><br /><p>Log into wifi, browse to <b style='padding: 0 5px;'>photo.app</b> and download your photos!</p></div>",
		"position": "bottomleft"
	},
	"flash": {
	  "enabled": false
	}
}
```
I'm running the latest version on a fresh Raspbian install on a RPi3. 

As always, any help is really appreciated! 

Rich

**Comment by philipptrenz** [comment]
Hi @RichyJ999, nether your Pi nor your camera will be able to process 100 frames per second, try to stick with the 10 fps, as @blaueQuelle suggested 😉

**Comment by RichyJ999** [comment]
Ha ha that's true! I tried values 1, 10, 20, 50 and 100 for the frame rate to see if any would work, but none made a difference.

I assume the rest of the code looks okay?

**Comment by timetolapse** [comment]
I have the same issue with EOS 1000D. But I can hear that the camera is flapping the mirror for Liveview.

**Comment by webworkerJoshua** [comment]
Looks like it as a canon issue? With both my Nikon D700 and D7100 it works out of the box.
Is anything in the console.log?

**Comment by forever80-dev** [comment]
I have same problem, the message in console is 
Nikon enable Liveview failed (0xa004: Invalid Status)

The boitier is D3500

**Comment by lal12** [comment]
I use it with my Canon EOS 750D. So I don't think it is a Canon issue.

**Comment by lal12** [comment]
But it is hard to anything about that, without having proper log output. 

You should set `"showDevTools": true` in `"init"` section of the config file, also start it from the terminal. After starting and maybe taking a picture attach the output in the terminal window and in the developer tools console to this issue.

**Comment by maximilianfriedrich** [comment]
Make sure your camera is in "manual" mode.
