### ISSUE TITLE
Text/button overlay

### ISSUE THREAD

**Issue by FizzyMUC** [philipptrenz/photo-booth#82]
Hi all,
I would like to add a button to the main screen (center) that just says sth like “take picture”.
Ideally, the startin point is the image grid, with the button. When I click the button, it disappears, timer starts, and then the image is taken.
Sadly I dont know where to start :( any ideas? Is this done in the CSS/HTML?

**Comment by FizzyMUC** [comment]
Instead of starting the LivePreview during the initialize function (in booth.js) I have moved it inside the trigger function (before the countdown starts). Now the booth starts with the grid view, however it does not respond to a click/tap on the touchscreen :(

**Comment by philipptrenz** [comment]
Hey, this can be achieved by adding just HTML/CSS as the photo sequence can be triggered by clicking anywhere at the screen

**Comment by FizzyMUC** [comment]
OK, understood. Will look into it on the weekend.
