### ISSUE TITLE
Change LiveView sequence?

### ISSUE THREAD

**Issue by FizzyMUC** [philipptrenz/photo-booth#83]
Hi all,
I want to have the following User Experience within the application:
Photobooth starts - Opens in grid view - click on display starts the liveview incl. the countdown - image is taken and shown for X seconds - back to grid view (without LiveView active).

I worked on the code a bit and instead of starting the LivePreview during the initialize function (in booth.js) I have moved it inside the trigger function (before the countdown starts). Now the booth starts with the grid view, however it does not respond to a click/tap on the touchscreen :(
Maybe someone has done the same in the past and is aware of a solution?

**Comment by philipptrenz** [comment]
Please provide your code changes, e.g. as a PR, so it can be reviewed

**Comment by FizzyMUC** [comment]
Will do, as soon as I figure out the "real" GitHub workflow :) Hopefully I can send it tonight.

**Comment by tigre-bleu** [comment]
This is an interesting workflow indeed.
