### ISSUE TITLE
Decentered live preview

### ISSUE THREAD

**Issue by trolhas** [philipptrenz/photo-booth#88]
-------------------------------

This photo-booth program works properly. The only problem is the "centering" of the live preview. The "liveview" works but it is shifted to the left ... Do you have an idea?
Thanks in advance for any help !!!!
Clément
-------------------------------
DSLR : Canon 600D ( USB )
RASPBERRY PI 3 B+
 DISPLAY SCREEN : MAKEASY - 7 inch LCD capacitive touch screen, HDMI
1024x600 resolution

**Comment by Simon-Pokorny** [comment]
Hi trolhas,
You can change that by adjusting the css attribute background-size to cover in app/css/main.css:

.live{
    position: absolute; top: 0; bottom: 0; right: 0; left: 0;
    background-repeat: no-repeat;
    **background-size: cover;**
    background-color: black;
}
