### ISSUE TITLE
How do I connect the button?

### ISSUE THREAD

**Issue by davide-brugnoni** [philipptrenz/photo-booth#90]
Hello I do not understand how to make the physical connection of the button to the raspberry you have by chance a photo to show me? I can not understand where to connect the resistance.
I am currently using the button of the sparkfun big dome push button.

**Comment by philipptrenz** [comment]
This should make it clear. It assumes, the circuit get's closed by pushing the button. And don't forget to enable the GPIOs within the config file 😉
![photo-booth_button](https://user-images.githubusercontent.com/11627598/62721101-cee48480-ba0b-11e9-8079-eaeebf94f53e.jpg)

**Comment by davide-brugnoni** [comment]
Thank you for your reply and for the image
