### ISSUE TITLE
Problem with RAW images

### ISSUE THREAD

**Issue by lal12** [philipptrenz/photo-booth#93]
I had the issue that my camera was set to take raw photos, however those can't be handled by the resize library. It will display `whoops` in the app and something like 
```
booth.js? [sm]:183 resizing image failed 
 Error: TIFFSetField: memory input: Unknown pseudo-tag 65538
TIFFSetField: memory input: Unknown pseudo-tag 65538
tiff2vips: unsupported tiff image type
```
in the dev tools. So I thought that maybe a hint about setting the camera to JPEG instead of RAW in the README would be a good idea.

**Comment by philipptrenz** [comment]
You‘re right, only JPEG Settings will work. I‘ll add the hint, thanks!
